# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Area de Conocimiento',
                'verbose_name_plural': 'Area de Conocimientos',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Distributivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Carrera')),
            ],
            options={
                'ordering': ('peridoacademico',),
                'verbose_name': 'Distributivo',
                'verbose_name_plural': 'Distributivo',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='local/%Y/%m', verbose_name='foto')),
            ],
            options={
                'ordering': ('persona',),
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('persona',),
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Estudiante')),
            ],
            options={
                'ordering': ('estudiante',),
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('alias', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('areaconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.AreaConocimiento')),
            ],
            options={
                'ordering': ('docente',),
                'verbose_name': 'Investigacion',
                'verbose_name_plural': 'Investigaciones',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechainicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('fechafin', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin')),
                ('cupo', models.IntegerField(default=0)),
                ('credito', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('horassemanal', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('fechainicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('fechafin', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin')),
                ('fechamatriculaordinaria', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha matricula ordinaria')),
                ('fechamatriculaextraordinaria', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha matricula ordinaria')),
                ('fechamatriculaespecial', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha matricula especial')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Modalidad')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Nivel Academico',
                'verbose_name_plural': 'Nivel Academico',
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de Fin')),
            ],
            options={
                'ordering': ('fechaInicio', 'fechaFin'),
                'verbose_name': 'Periodo Academico',
                'verbose_name_plural': 'Periodos Academicos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=200)),
                ('apellidos', models.CharField(default='', max_length=200)),
                ('documento', models.CharField(default='', max_length=20)),
                ('correo', models.CharField(default='', max_length=200)),
                ('fechaNacimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
                ('celular', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('direccion', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ('nombres',),
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='SubAreaConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Sub Area de Conocimiento',
                'verbose_name_plural': 'Sub Area de Conocimiento',
            },
        ),
        migrations.CreateModel(
            name='SubAreaConocimientoEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Sub Area de Conocimiento Especifico',
                'verbose_name_plural': 'Area de Conocimiento Especifico',
            },
        ),
        migrations.CreateModel(
            name='TipoNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Tipo Nivel',
                'verbose_name_plural': 'Tipos de Niveles',
            },
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('areaconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.AreaConocimiento')),
                ('areaconocimientoespecifico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.SubAreaConocimientoEspecifico')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Docente')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Grado')),
                ('subareaconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.SubAreaConocimiento')),
                ('tiponivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.TipoNivel')),
            ],
            options={
                'ordering': ('docente',),
                'verbose_name': 'Investigacion',
                'verbose_name_plural': 'Investigaciones',
            },
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Sesion'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='areaconocimientoespecifico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.SubAreaConocimientoEspecifico'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Docente'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='subareaconocimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.SubAreaConocimiento'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Materia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Persona'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Persona'),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Docente'),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Facultad'),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Materia'),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Paralelo'),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='peridoacademico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.PeriodoAcademico'),
        ),
        migrations.AddField(
            model_name='distributivo',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Semestre'),
        ),
    ]
